#unbind '"'
#bind-key '"' split-window -v -c "#{pane_current_path}"

#unbind %
#bind-key % split-window -h -c "#{pane_current_path}"

#bind-key r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

bind-key S-Left swap-window -t -1\; select-window -t -1
bind-key S-Right swap-window -t +1\; select-window -t +1

# https://github.com/laktak/extrakto
# pref + tab
set -g @plugin 'laktak/extrakto'
