# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(282827)
$foreground = rgb(F1F1EE)
$color0 = rgb(4D4D4D)
$color1 = rgb(1D1E1C)
$color2 = rgb(212220)
$color3 = rgb(4C4E4A)
$color4 = rgb(755537)
$color5 = rgb(5C5E59)
$color6 = rgb(A2A19B)
$color7 = rgb(E3E2DE)
$color8 = rgb(9F9E9B)
$color9 = rgb(272826)
$color10 = rgb(2C2D2B)
$color11 = rgb(656963)
$color12 = rgb(9C7249)
$color13 = rgb(7A7E77)
$color14 = rgb(D8D6CE)
$color15 = rgb(E3E2DE)
