# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F1F1EE
background         #282827
cursor             #8F8F8C

active_tab_foreground     #282827
active_tab_background     #F1F1EE
inactive_tab_foreground   #F1F1EE
inactive_tab_background   #282827

active_border_color   #F1F1EE
inactive_border_color #282827
bell_border_color     #1D1E1C

color0      #4D4D4D
color1		#1D1E1C
color2		#212220
color3		#4C4E4A
color4		#755537
color5		#5C5E59
color6		#A2A19B
color7		#E3E2DE
color8		#9F9E9B
color9		#272826
color10		#2C2D2B
color11		#656963
color12		#9C7249
color13		#7A7E77
color14		#D8D6CE
color15		#E3E2DE
